server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
      - id: member_mgmt_route
        uri: lb:http://MEMBER-MGMT-SERVICE
        predicates:
        - Path=/membermgmtservice/**
        - Header=member,memberno
        - Before=2023-03-16T07:07:07Z
        filters:
        - RewritePath=/membermgmtservice(?<segment>/?.*),$\{segment}
        - CircuitBreaker=slow
      - id: pharmacy_route
        uri: lb:http://PHARMACY-SERVICE
        predicates:
        - Path=/pharmacyservice/**
        filters:
        - RewritePath=/pharmacyservice(?<segment>/?.*),$\{segment}
        
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka