spring:
  main:
    web-application-type: NONE
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8889/eureka
 #defaultZone: http://localhost:8889/eureka, http://localhost:9898/eureka    
   